### ISSUE TITLE
Crash on non-UTF-8 input

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [tritongrader/tritongrader#47]
We can't really trust user input here when our purpose is to test invalid programs.
```
Traceback (most recent call last):
  File "/autograder/pa3-autograder/grade.py", line 111, in <module>
    results = formatter.execute()
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 218, in execute
    "tests": [self.format_test(i) for i in self.test_cases],
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 218, in <listcomp>
    "tests": [self.format_test(i) for i in self.test_cases],
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 205, in format_test
    item.update(super().format_test(test))
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 38, in format_test
    return self.formatters[type(test)](test)
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 166, in format_io_test
    (self.generate_html_diff(test) if self.html_diff else self.basic_io_output(test)),
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/formatter.py", line 120, in basic_io_output
    test.actual_stdout,
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/test_case/io_test_case.py", line 82, in actual_stdout
    return self.runner.stdout
  File "/usr/local/lib/python3.10/dist-packages/tritongrader/runner.py", line 103, in stdout
    return fp.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 25: invalid start byte
```

**Comment by jyu283** [comment]
Do you have a proposed fix? To add a simple try-catch statement and report decode failure?

**Comment by DuckDuckWhaleUCSD** [comment]
Something like that, either reporting the decoding error message back to the user or always read in binary mode and opportunistically parse as UTF-8 and do normal text diff, and if that doesn't work fallback to binary hex diff. I just don't know how to handle errors in Python -- raising errors or returning Rust-like enums (tagged unions) containing either the success result or the error type?
